/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum MemberProfileVisibilityMapAddress {
    Private = "Private",
    ClientVisible = "ClientVisible",
    Public = "Public",
}

export enum MemberProfileVisibilityMapPhone {
    Private = "Private",
    ClientVisible = "ClientVisible",
    Public = "Public",
}

export class MemberProfileVisibilityMap extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    address?: MemberProfileVisibilityMapAddress;

    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone?: MemberProfileVisibilityMapPhone;
}
