/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum PhoneChannel {
    PhoneCall = "PhoneCall",
    Sms = "SMS",
}

export enum ChannelPendingVerification {
    PhoneCall = "PhoneCall",
    Sms = "SMS",
}

export enum PhoneStatus {
    Pending = "Pending",
    Verified = "Verified",
}

export class Phone extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "channel" })
    channel?: PhoneChannel;

    @SpeakeasyMetadata()
    @Expose({ name: "channelPendingVerification" })
    channelPendingVerification?: ChannelPendingVerification;

    @SpeakeasyMetadata()
    @Expose({ name: "number" })
    number?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "numberPendingVerification" })
    numberPendingVerification?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: PhoneStatus;
}
