/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum PreviouslyBilledPackage {
    None = "None",
    Benefits = "Benefits",
    Essentials = "Essentials",
    Professional = "Professional",
    Corporate = "Corporate",
}

export enum PreviouslyBilledPackageTier {
    Basic = "Basic",
    Premium = "Premium",
}

export enum PreviouslyBilledTerm {
    Yearly = "Yearly",
    Monthly = "Monthly",
}

export class PreviouslyBilled extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "package" })
    package?: PreviouslyBilledPackage;

    @SpeakeasyMetadata()
    @Expose({ name: "packageTier" })
    packageTier?: PreviouslyBilledPackageTier;

    @SpeakeasyMetadata()
    @Expose({ name: "term" })
    term?: PreviouslyBilledTerm;
}
