/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum Benefits {
    Disabled = "Disabled",
    Enabled = "Enabled",
    Pending = "Pending",
}

export enum Payments {
    Disabled = "Disabled",
    Enabled = "Enabled",
    Pending = "Pending",
}

export class ServiceStatus extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "benefits" })
    benefits?: Benefits;

    @SpeakeasyMetadata()
    @Expose({ name: "payments" })
    payments?: Payments;
}
