/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum SubscriptionCreateRequestPackage {
    None = "None",
    Benefits = "Benefits",
    Essentials = "Essentials",
    Professional = "Professional",
    Corporate = "Corporate",
}

export enum SubscriptionCreateRequestPackageTier {
    Basic = "Basic",
    Premium = "Premium",
}

export enum SubscriptionCreateRequestTerm {
    Yearly = "Yearly",
    Monthly = "Monthly",
}

export class SubscriptionCreateRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "discountCode" })
    discountCode?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "package" })
    package?: SubscriptionCreateRequestPackage;

    @SpeakeasyMetadata()
    @Expose({ name: "packageTier" })
    packageTier?: SubscriptionCreateRequestPackageTier;

    @SpeakeasyMetadata()
    @Expose({ name: "paymentMethodId" })
    paymentMethodId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "planId" })
    planId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "subscriptionGrantId" })
    subscriptionGrantId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "term" })
    term?: SubscriptionCreateRequestTerm;
}
