/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum SubscriptionGrantUpdateRequestPackage {
    None = "None",
    Benefits = "Benefits",
    Essentials = "Essentials",
    Professional = "Professional",
    Corporate = "Corporate",
}

export enum SubscriptionGrantUpdateRequestPackageTier {
    Basic = "Basic",
    Premium = "Premium",
}

export class SubscriptionGrantUpdateRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "package" })
    package?: SubscriptionGrantUpdateRequestPackage;

    @SpeakeasyMetadata()
    @Expose({ name: "packageTier" })
    packageTier?: SubscriptionGrantUpdateRequestPackageTier;
}
